services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: belgram
      POSTGRES_USER: belgram
      POSTGRES_PASSWORD: belgram
    ports:
      - "5432:5432"
    volumes:
      - belgram_postgres:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  belgram_postgres:
